coupon.provider=inmem
coupon.init-data=true

spring.jpa.defer-datasource-initialization=true

logging.level.it.schwarz.jobs.review.coupon=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE 