spring.jpa.defer-datasource-initialization=true
coupon.provider=inmem

logging.level.it.schwarz.jobs.review.coupon=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE 