### Set your production properties here
coupon.provider=jpa
coupon.init-data=false

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never

logging.level.it.schwarz.jobs.review.coupon=INFO
logging.level.org.springframework.web=WARN
logging.level.org.hibernate.SQL=WARN