### Set your production properties here
spring.jpa.defer-datasource-initialization=true

logging.level.it.schwarz.jobs.review.coupon=INFO
logging.level.org.springframework.web=WARN
logging.level.org.hibernate.SQL=WARN